name: Release & Publish to NPM

on: workflow_dispatch

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Initialize Git user
        run: |
          git config --global user.name "krishna"
          git config --global user.email "krishna5050@gmail.com"
      - name: Initialize Npm config
        run: npm config set //registry.npmjs.org/:_authToken ${{secrets.NPM_TOKEN}}
      - name: Release
        run: bun run release --ci
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
